### ISSUE TITLE
Volvo 2FA

### ISSUE THREAD

**Issue by FireWizard52** [nikagl/volvo#2]
Hallo Nika,

Ik benader je even via je eigen Github pagina, omdat ik vermoedelijk tegen hetzelde probleem aanloop met de 2FA voor mijn Volvo.
Ik ben toch al een tijdje opzoek naar een oplossing totdat ik tegen je post aanliep op: https://github.com/akamming/Domoticz_VolvoRecharge_Plugin/issues/12

Nadat mijn authorisatie gestopt was i.v.m de introductie van 2FA door Volvo heb ik mijn Node=RED flow omgebouwd voor 2FA.
Helaas is dat nog niet goed gelukt.

De situatie is nu als volgt:
- Ik ontvang een ogenschijnlijk correcte "access code", maar zodra ik een endpoint benader ontvang ik:
   
error: object
message: "FORBIDDEN"
description: "Access is denied"

Dit is hetzelfde als jij vermeldde in het issue op akammings Github pagina.

Zou je jouw Headers willen delen?

Ik heb momenteel het volgende:

URL: https://volvoid.eu.volvocars.com/as/authorization.oauth2?" + msg.url_query_params + "&" + msg.scope
de query paramanters zijn als volgt:

`client_id=h4Yf0b&response_type=code&acr_values=urn:volvoid:aal:bronze:2sv&response_mode=pi.flow`

de scope is als volgt:

`openid%20vehicle:attributes%20conve:brake_status%20conve:climatization_start_stop%20conve:command_accessibility%20conve:commands%20conve:diagnostics_engine_status%20conve:diagnostics_workshop%20conve:doors_status%20conve:engine_status%20conve:environment%20conve:fuel_status%20conve:honk_flash%20conve:lock%20conve:lock_status%20conve:navigation%20conve:odometer_status%20conve:trip_statistics%20conve:tyre_status%20conve:unlock%20conve:vehicle_relation%20conve:warnings%20conve:windows_status%20energy:battery_charge_level%20energy:charging_connection_status%20energy:charging_system_status%20energy:electric_range%20energy:estimated_charging_time%20energy:recharge_status`

en de Headers:

`{"Authorization":"Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=","User-Agent":"okhttp/4.10.0","Accept-Encoding":"gzip","Content-Type":"application/json; charset=utf-8"}`

Dit resulteert in:

"USERNAME_PASSWORD_REQUIRED"

https://volvoid.eu.volvocars.com/pf-ws/authn/flows/FQK6rjubxf?action=checkUsernamePassword

heeft volgende Headers:

{
    "Authorization": "Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=",
    "User-Agent": "okhttp/4.10.0",
    "Accept-Encoding": "gzip",
    "Content-Type": "application/json; charset=utf-8",
    "x-xsrf-header": "PingFederate"
}

en ik stuur de Username en Password mee in de body van het request als een object.

Resutaat: OTP_REQUIRED

Dan: https://volvoid.eu.volvocars.com/pf-ws/authn/flows/WE7lK518YV?action=checkOtp
Dezelfde Header en de payload in de body als een object otp: 123456

Daarna ontvan ik: OTP_VERIFIED
en vervolgens stuur ik: https://volvoid.eu.volvocars.com/pf-ws/authn/flows/WE7lK518YV?action=continueAuthentication

Dit geeft uiteidelijk:COMPLETED
Nog steeds dezelfde Header

Daarna doe ik een request voor het access token:
https://volvoid.eu.volvocars.com/as/token.oauth2?grant_type=authorization_code&code=" + msg.payload.authorizeResponse.code

Dat authorizeResponse code id de access code beginnende met ey..

Headers zijn:

    "Authorization": "Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=",
    "x-xsrf-header": "PingFederate"

en in de body: het client_id h4Yf0b

De requests van de endpoints hebben altijd gewerkt en werken ook met het Demo token, dus ik vermoed dat hier ook wat mis is met de Headers of eventueel de cookies.

Misschien kun je me een stap vooruit helpen met jouw configuratie.

Bij voorbaat dank.

Herman

**Comment by nikagl** [comment]
Hi Herman,

Het belangrijkste is dat je de headers goed meegeeft zoals in de code van Domoticz:

url_params = ("?client_id=h4Yf0b"
              "&response_type=code"
              "&acr_values=urn:volvoid:aal:bronze:2sv"
              "&response_mode=pi.flow"
              "&scope=openid email profile care_by_volvo:financial_information:invoice:read care_by_volvo:financial_information:payment_method care_by_volvo:subscription:read customer:attributes customer:attributes:write order:attributes vehicle:attributes tsp_customer_api:all conve:brake_status conve:climatization_start_stop conve:command_accessibility conve:commands conve:diagnostics_engine_status conve:diagnostics_workshop conve:doors_status conve:engine_status conve:environment conve:fuel_status conve:honk_flash conve:lock conve:lock_status conve:navigation conve:odometer_status conve:trip_statistics conve:tyre_status conve:unlock conve:vehicle_relation conve:warnings conve:windows_status energy:battery_charge_level energy:charging_connection_status energy:charging_system_status energy:electric_range energy:estimated_charging_time energy:recharge_status vehicle:attributes")

Ik heb delen eruit gehaald omdat ik het liefst zo clean mogelijke code gebruik, maar toen ik dat deed kreeg ik wel een token, maar werkte dat token dus niet...

Ik denk dat ik morgen pas tijd heb om jouw hele bericht stap voor stap door te nemen...

Groet,

Nika.

**Comment by nikagl** [comment]
Als je dit secuur, stap voor stap, naspeelt dan werkt het altijd goed (ik heb het eerst in Postman gezet en daarna naar mijn eigen home automation code):

https://github.com/akamming/Domoticz_VolvoRecharge_Plugin/blob/main/authorize.py

**Comment by FireWizard52** [comment]
Goedenavond Nika,

**Probleem opgelost.**

Hartelijk dank voor je antwoord.
Dit was de trigger voor de oplossing.

Mijn 2FA flow was opgebouwd in Node-RED en functioneerde (achteraf gezien) al lange tijd correct.
Ik besloot hem helemaal opnieuw op te bouwen, maar dan in pure Javascript en toen liep ik er al snel tegenaan.
Ik had de scope opgebouwd , echter zonder "scope = openid  etc", maar alleen de elementen. Dus "openid etc"
Dit betekende dus simpelweg dat ik me niet geauthorizeerd voor alle scopes! Uiteraard vindt Volvo dat geen probleem, maar je krijgt dan ook geen toegang tot een endpoint.

Je schreef ook:

> Ik heb delen eruit gehaald omdat ik het liefst zo clean mogelijke code gebruik, maar toen ik dat deed kreeg ik wel een token, maar werkte dat token dus niet...

Ik heb ook deze voorkeur. Wat er niet in hoeft, laat ik het liefst weg.

Ik heb de authorisatie dus ook behoorlijk opgeschoond.

Hetgeen bij mij werkt is het volgende:

```
URL: https://volvoid.eu.volvocars.com/as/authorization.oauth2?" + msg.url_params + "&" + msg.scope
de msg.url_params parameters zijn als volgt:
```

`client_id=h4Yf0b&response_type=code&acr_values=urn:volvoid:aal:bronze:2sv&response_mode=pi.flow`

de scope is als volgt:

`scope=openid%20vehicle:attributes%20conve:brake_status%20conve:climatization_start_stop%20conve:command_accessibility%20conve:commands%20conve:diagnostics_engine_status%20conve:diagnostics_workshop%20conve:doors_status%20conve:engine_status%20conve:environment%20conve:fuel_status%20conve:honk_flash%20conve:lock%20conve:lock_status%20conve:navigation%20conve:odometer_status%20conve:trip_statistics%20conve:tyre_status%20conve:unlock%20conve:vehicle_relation%20conve:warnings%20conve:windows_status%20energy:battery_charge_level%20energy:charging_connection_status%20energy:charging_system_status%20energy:electric_range%20energy:estimated_charging_time%20energy:recharge_status`

en de Headers:

`{"Authorization":"Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc="`

Dit resulteert in:

`"USERNAME_PASSWORD_REQUIRED"
`
`https://volvoid.eu.volvocars.com/pf-ws/authn/flows/FQK6rjubxf?action=checkUsernamePassword`

heeft volgende Headers:

```
{
"Authorization": "Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=",
"x-xsrf-header": "PingFederate"
}

```
en ik stuur de Username en Password mee in de body van het request als een object.

Resutaat: `OTP_REQUIRED`

Dan: `https://volvoid.eu.volvocars.com/pf-ws/authn/flows/WE7lK518YV?action=checkOtp`
Dezelfde Header en de payload in de body als een object `otp: 123456`

Daarna ontvang ik: `OTP_VERIFIED`
en vervolgens stuur ik: `https://volvoid.eu.volvocars.com/pf-ws/authn/flows/WE7lK518YV?action=continueAuthentication`
Dezelfde Header

Dit geeft uiteidelijk:`COMPLETED`
Nog steeds dezelfde Header

Daarna doe ik een request voor het access token:
`https://volvoid.eu.volvocars.com/as/token.oauth2?grant_type=authorization_code&code=" + msg.payload.authorizeResponse.code`

Dan ontvang ik de access code beginnende met ey..

Headers zijn:

"```
Authorization": "Basic aDRZZjBiOlU4WWtTYlZsNnh3c2c1WVFxWmZyZ1ZtSWFEcGhPc3kxUENhVXNpY1F0bzNUUjVrd2FKc2U0QVpkZ2ZJZmNMeXc=",
"x-xsrf-header": "PingFederate"
```

Dus ik heb het e.e.a uit de Headers gesloopt en ook de scope ontdaan van overtollige zaken

Binnen Node RED moet ik wel zorgen dat cookies terug wordt gestuurd (msg.cookies = msg.responseCookies).
Het schijnt dat Python dat autmatisch doet.

Dus probleem is opgelost en je hoeft je settings dus morgen niet meer na te kijken, tenzij je er n.a.v. mijn bericht nog iets wilt uithalen 

Nogmaals bedankt voor je antwoord.

Fijn weekend en groet,

Herman

**Comment by nikagl** [comment]
Top, dank voor de moeite om het vast te leggen en de headers te testen. Kan ik mijn code mooi op aanpassen 👍
